### ISSUE TITLE
不知道SDK 如何使用，有没有文档说明呢

### ISSUE THREAD

**Issue by TT-struggleofoneself** [Bepal/bepalcore-oc#2]
不知道SDK 如何使用，有没有文档说明呢

**Comment by chenluyong** [comment]
您是否了解过 EOS、GXC 公链呢？

**Comment by TT-struggleofoneself** [comment]
大概了解过，不是很熟悉，只能算了解过  有没有Demo提供呢 大神

**Comment by chenluyong** [comment]
在具备OC编程环境下，编译该代码。
启动测试用例，来了解几个基础的操作流程。
例如：BIP44的公私钥推导、签名，交易构造等；

您现在issue没有具体的问题，我没办法给予你合适的帮助。

**Comment by TT-struggleofoneself** [comment]
我下载了您的源代码， 里面是framwork 的， 我先创建了一个工程准备使用您的framwork， 但是不知道如何开始写，因为没有注释， 没有文档说明  如果大神有一个Demo  或者文档的话，那就方便多了

**Comment by TT-struggleofoneself** [comment]
我主要是想 实现EOS 钱包功能

**Comment by chenluyong** [comment]
[测试用例](https://github.com/Bepal/bepalcore-oc/blob/master/BepalCoreTests/EOSTest.m) 是否顺利执行了呢？

**Comment by TT-struggleofoneself** [comment]
我刚看到了，还没执行，我试下   谢谢了

**Comment by TT-struggleofoneself** [comment]
刚刚看了下貌似可以执行， 现在生成了公钥和私钥 你test里面是通过助记词生成的公钥私钥吧。   EOS 的。   另外大神关于EOS 我有些没有明白的是， 它的公钥和私钥 如何与账号信息关联的呢？   另外关于EOS 的流程也有些不太明白， 我创建了一个私钥之后 还需要支付EOS 之后才能创建一个真的钱包， 在这一步会把账号和公钥私钥绑定在一起。 那么这个付款的过程是否就是普通的转账呢。我感觉不是， 大神能否帮我梳理下这个思路呢。以及每一步对应你的test方法是哪个呢，将会非常感谢

**Comment by chenluyong** [comment]
或许 [EOS Wiki](https://developers.eos.io/eosio-nodeos/docs/overview-1) 可以更好的帮助你度过初学的难关。
除此之外，我可能也没有更好的建议。
